/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-04-17 20:34:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class adminPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String user = (String) session.getAttribute("FirstName");
    String admin = (String) session.getAttribute("adminName");
    String addTrain = (String) session.getAttribute("addTrainError");
    String trainmsg = (String) session.getAttribute("trainAdd");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=, initial-scale=1.0\">\n");
      out.write("    <title>Admin Login</title>\n");
      out.write("    <link rel=\"icon\" href=\"Image/logo.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"AdminPagestyle.css\">\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("    function generateStops() {\n");
      out.write("        let stops = document.getElementById(\"stops\").value;\n");
      out.write("        let container = document.getElementById(\"stationDetails\");\n");
      out.write("        container.innerHTML = \"\"; // Clear previous entries\n");
      out.write("\n");
      out.write("        for (let i = 1; i <= stops; i++) {\n");
      out.write("            container.innerHTML += `\n");
      out.write("                    <h3>Stop ${i}</h3>\n");
      out.write("                    <label>STATION CODE</label><br>\n");
      out.write("                    <input type=\"text\" name=\"stationCode${i}\" required><br>\n");
      out.write("                    <label>STATION NAME</label><br>\n");
      out.write("                    <input type=\"text\" name=\"stationName${i}\" required><br>\n");
      out.write("                    <label>ARRIVAL TIME</label><br>\n");
      out.write("                    <input type=\"time\" name=\"arrival${i}\"><br>\n");
      out.write("                    <label>DEPARTURE TIME</label><br>\n");
      out.write("                    <input type=\"time\" name=\"departure${i}\"><br><br>\n");
      out.write("                `;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("<div class=\"nav\">\n");
      out.write("    <h2>Railway Reservation System</h2>\n");
      out.write("</div>\n");
      out.write("<div class=\"nav2\">\n");
      out.write("    ");
 if(user != null) {
      out.write("\n");
      out.write("    <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( user );
      out.write(" &emsp; </h4>\n");
      out.write("    <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("    ");
}else if(admin != null) {
      out.write("\n");
      out.write("    <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( admin );
      out.write(" &emsp; </h4>\n");
      out.write("    <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("    ");
}else{
      out.write("\n");
      out.write("    <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome, Guest! </h4>\n");
      out.write("    ");
}
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div class=\"nav1\">\n");
      out.write("    <img src=\"Image/logo.png\" alt=\"Railway logo\">\n");
      out.write("    <a href=\"index.jsp\" target=\"_parent\">HOME</a>\n");
      out.write("    ");
 if(user == null && admin ==null ) {
      out.write("\n");
      out.write("    <a href=\"login.jsp\">USER LOGIN</a>\n");
      out.write("    <a href=\"agent.jsp\">AGENT LOGIN</a>\n");
      out.write("    ");
}else if(admin == null && user!=null){
      out.write("\n");
      out.write("    <a href=\"login.jsp\">USER LOGIN</a>\n");
      out.write("    <a href=\"agent.jsp\">AGENT LOGIN</a>\n");
      out.write("    ");
}
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if(admin==null){
      out.write("\n");
      out.write("    <a href=\"register.jsp\">REGISTER</a>\n");
      out.write("    ");
}
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("    <a href=\"train-schedule.jsp\">TRAIN SCHEDULE</a>\n");
      out.write("    <a href=\"contact.jsp\">CONTACT US</a>\n");
      out.write("    <a href=\"help.jsp\">HELP & SUPPORT</a>\n");
      out.write("\n");
      out.write("    ");
 if(admin!=null){
      out.write("\n");
      out.write("    <a href=\"adminPage.jsp\">ADMIN PAGE</a>\n");
      out.write("    ");
}
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <button type=\"submit\" popovertarget=\"AddTrain\" class=\"btn btn-1\">Add Train</button>\n");
      out.write("    <button type=\"submit\" popovertarget=\"cancleTrain\" class=\"btn btn-2\">Cancle Train</button>\n");
      out.write("    <button type=\"submit\" popovertarget=\"UpdateTrain\" class=\"btn btn-3\">Update Train</button>\n");
      out.write("    <button type=\"submit\" popovertarget=\"DeleteTrain\" class=\"btn btn-4\">Delete Train</button>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div popover id=\"AddTrain\" class=\"AddTrain\">\n");
      out.write("        <h1>ADD TRAIN</h1>\n");
      out.write("        <form action=\"AddTrain\" method=\"post\">\n");
      out.write("            <label for=\"add1\">Train Number</label>\n");
      out.write("            <br>\n");
      out.write("            <input type=\"text\" name=\"TrainNo\" id=\"add1\" maxlength=\"6\" required>\n");
      out.write("            <br>\n");
      out.write("            <label for=\"add2\">Train Name</label>\n");
      out.write("            <br>\n");
      out.write("            <input type=\"text\" name=\"TrainName\" required id=\"add2\">\n");
      out.write("            <br>\n");
      out.write("            <h2>ROUTE DETAILS</h2>\n");
      out.write("            <!-- <br> -->\n");
      out.write("            <!-- for loop for total no of stops -->\n");
      out.write("\n");
      out.write("            <div class=\"sourceDetails\">\n");
      out.write("                <!-- <label for=\"source\">SOURCE</label> -->\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" name=\"source\" placeholder=\"SOURCE\" required id=\"source\" >\n");
      out.write("                <br>\n");
      out.write("                <!-- <label for=\"dest\">DESTINATION</label> -->\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" name=\"destination\" placeholder=\"DESTINATION\" required id=\"dest\">\n");
      out.write("                <br>\n");
      out.write("                <input type=\"text\" name=\"coach\" placeholder=\"Total Coach\" required id=\"coach\">\n");
      out.write("                <br>\n");
      out.write("                <input type=\"time\" name=\"departure\" placeholder=\"Departure Time\" required id=\"departure\">\n");
      out.write("            </div>\n");
      out.write("            <br>\n");
      out.write("            <input type=\"number\" name=\"stops\" id=\"stops\"  placeholder=\"Total NO. OF STOPS\" style=\"text-align: center;width: 300px;\">\n");
      out.write("            <br><br>\n");
      out.write("            <button type=\"button\" class=\"btn-generate\" onclick=\"generateStops()\">Generate</button>\n");
      out.write("            <div id=\"stationDetails\"></div>\n");
      out.write("\n");
      out.write("            <!-- Train Frequency  -->\n");
      out.write("            <h2>Train Frequency</h2>\n");
      out.write("            <div class=\"day1\">\n");
      out.write("                <label for=\"mon\">MON</label>\n");
      out.write("                <label for=\"tue\">TUE</label>\n");
      out.write("                <label for=\"wed\">WED</label>\n");
      out.write("                <label for=\"thu\">THU</label>\n");
      out.write("                <label for=\"fri\">FRI</label>\n");
      out.write("                <label for=\"sat\">SAT</label>\n");
      out.write("                <label for=\"sun\">SUN</label>\n");
      out.write("                <label for=\"daily\">DAILY</label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"day\">\n");
      out.write("                <input type=\"checkbox\" name=\"mon\" id=\"mon\">\n");
      out.write("                <input type=\"checkbox\" name=\"tue\" id=\"tue\">\n");
      out.write("                <input type=\"checkbox\" name=\"wed\" id=\"wed\">\n");
      out.write("                <input type=\"checkbox\" name=\"thu\" id=\"thu\">\n");
      out.write("                <input type=\"checkbox\" name=\"fri\" id=\"fri\">\n");
      out.write("                <input type=\"checkbox\" name=\"sat\" id=\"sat\">\n");
      out.write("                <input type=\"checkbox\" name=\"sun\" id=\"sun\">\n");
      out.write("                <input type=\"checkbox\" name=\"daily\" id=\"daily\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"btn\">\n");
      out.write("                <button type=\"submit\" class=\"b1\">ADD</button>\n");
      out.write("                <button type=\"reset\" class=\"b2\">RESET</button>\n");
      out.write("                ");
if(trainmsg != null){
      out.write("\n");
      out.write("                <script>\n");
      out.write("                    alert(");
      out.print( trainmsg );
      out.write(");\n");
      out.write("                </script>\n");
      out.write("                ");
}else{
      out.write("\n");
      out.write("                <script>\n");
      out.write("                    alert(\"Train Added  Successfully.\");\n");
      out.write("                </script>\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    <div popover id=\"cancleTrain\">Cancle Train</div>\n");
      out.write("    <div popover id=\"UpdateTrain\">Update Train</div>\n");
      out.write("    <div popover id=\"DeleteTrain\">Delete Train</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
