/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-04-17 20:34:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class agent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>IRCTC Login Page</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"agent_Login.css\">\n");
      out.write("</head>\n");
      out.write("<body> \n");
      out.write("    <form action=\"LoginAdmin\" method=\"post\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"login-box\">\n");
      out.write("            <h1>Agent Log in</h1>\n");
      out.write("            <p id=\"tag\">You Are An User ? <a href=\"login.html\">User Login</a></p>\n");
      out.write("                <label for=\"username\">Username</label>\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter your username\" required>\n");
      out.write("                \n");
      out.write("                <label for=\"password\">Password</label>\n");
      out.write("                <div class=\"password-field\">\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required>\n");
      out.write("                    <span class=\"show-password\">Show</span>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"remember-me\">\n");
      out.write("                    <input type=\"checkbox\" id=\"keep-logged-in\">\n");
      out.write("                    <label for=\"keep-logged-in\">Keep me logged in</label>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"login-btn\">Log in</button>\n");
      out.write("\n");
      out.write("            ");

                String error = (String) session.getAttribute("Adminerror");
                if (error != null) {
            
      out.write("\n");
      out.write("\n");
      out.write("            <script>\n");
      out.write("                alert(\"");
      out.print( error );
      out.write("\");\n");
      out.write("            </script>\n");
      out.write("            ");

                    session.removeAttribute("error");
                }
            
      out.write("\n");
      out.write("                \n");
      out.write("                <div class=\"help-links\">\n");
      out.write("                    <a href=\"#\">Forgot password?</a>\n");
      out.write("                    <a href=\"#\">Can't log in?</a>\n");
      out.write("                    <a href=\"index.html\">Home</a>\n");
      out.write("                </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <footer style=\"background-color: #222; color: #fff; padding: 20px 0; \" >\n");
      out.write("        <div style=\"display: flex; justify-content: space-around; flex-wrap: wrap; padding: 20px;\">\n");
      out.write("          \n");
      out.write("          <!-- About Section -->\n");
      out.write("          <div style=\"max-width: 300px;\">\n");
      out.write("            <h4>About Us</h4>\n");
      out.write("            <p >We aim to provide a seamless railway ticket booking experience, offering real-time updates, schedule management, and customer support.</p>\n");
      out.write("          </div>\n");
      out.write("      \n");
      out.write("          <!-- Quick Links -->\n");
      out.write("          <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Quick Links</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("              <li><a href=\"index.html\" style=\"color: #fff; text-decoration: none;\">Home</a></li>\n");
      out.write("              <li><a href=\"book.html\" style=\"color: #fff; text-decoration: none;\">Book Ticket</a></li>\n");
      out.write("              <li><a href=\"train-schedule.html\" style=\"color: #fff; text-decoration: none;\">Train Schedule</a></li>\n");
      out.write("              <li><a href=\"contact.html\" style=\"color: #fff; text-decoration: none;\">Contact Us</a></li>\n");
      out.write("              <li><a href=\"help.html\" style=\"color: #fff; text-decoration: none;\">FAQs</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("      \n");
      out.write("          <!-- Customer Support -->\n");
      out.write("          <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Customer Support</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("              <li>Helpline: 7666300048</li>\n");
      out.write("              <li>Email: tejasdevgharkar12@gmail.com</li>\n");
      out.write("              <li><a href=\"feedback.html\" style=\"color: #fff; text-decoration: none;\">Submit Feedback</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("      \n");
      out.write("          <!-- Social Media Links -->\n");
      out.write("          <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Follow Us</h4>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Facebook</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Twitter</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff;\">Instagram</a>\n");
      out.write("          </div>\n");
      out.write("      \n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Copyright Section -->\n");
      out.write("        <div style=\"text-align: center; border-top: 1px solid #555; padding: 10px 0;\">\n");
      out.write("          <p>&copy; 2024 Railway Reservation System. All rights reserved.</p>\n");
      out.write("        </div>\n");
      out.write("      </footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
