/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2026-03-31 09:51:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class BookingPassenger_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String user = (String) session.getAttribute("FirstName");
    String admin = (String) session.getAttribute("adminName");
    if (user == null){
        response.sendRedirect("/Railway_Reservation_System/login.jsp");
    }

      out.write('\n');
      out.write('\n');

    String trainNo = request.getParameter("train_no");

      out.write('\n');
      out.write('\n');

    String Success = (String) session.getAttribute("selectedDate");
    if (Success != null) {

      out.write("\n");
      out.write("<script>\n");
      out.write("    alert(\"");
      out.print( Success );
      out.write("\");\n");
      out.write("</script>\n");

        session.removeAttribute("selectedDate");
    }

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Booking</title>\n");
      out.write("    <link rel=\"icon\" href=\"Image/logo.png\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"BookingPassengerStyle.css\">\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function generatePassenger() {\n");
      out.write("        let passenger = document.getElementById(\"passenger\").value;\n");
      out.write("        let container = document.getElementById(\"details\");\n");
      out.write("        let payment = document.getElementById(\"payment\");\n");
      out.write("        container.innerHTML = \"\"; // Clear previous entries\n");
      out.write("\n");
      out.write("        // Create table structure\n");
      out.write("        if (passenger == \"\") {\n");
      out.write("            alert(\"Total Number Of Passenger are Empty\");\n");
      out.write("        }\n");
      out.write("        else if (passenger > 0) {\n");
      out.write("            let table = `\n");
      out.write("        <table border=\"1\" style=\"width: 100%; border-collapse: collapse; text-align: left;\">\n");
      out.write("            <thead>\n");
      out.write("                <tr style=\"background-color:lightblue;text-align:center;height:40px;letter-spacing:4px\">\n");
      out.write("                    <th>Passenger No</th>\n");
      out.write("                    <th>Passenger Name</th>\n");
      out.write("                    <th>Passenger Age</th>\n");
      out.write("                    <th>Passenger Gender</th>\n");
      out.write("                </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("    `;\n");
      out.write("\n");
      out.write("            for (let i = 1; i <= passenger; i++) {\n");
      out.write("                table += `\n");
      out.write("            <tr style=\"height:60px\">\n");
      out.write("                <td style=\"text-align:center;font-weight:700\">Passenger ${i}</td>\n");
      out.write("                <td style=\"text-align:center;\">\n");
      out.write("                    <input type=\"text\" name=\"passengerName${i}\" style=\"text-align:center;width:95%;height:50px;border-radius:10px;border:none;background-color:#d6dce2\" required>\n");
      out.write("                </td>\n");
      out.write("                <td style=\"text-align:center;\">\n");
      out.write("                    <input type=\"number\" name=\"passengerAge${i}\" min=\"1\" required style=\"text-align:center;width:95%;height:50px;border-radius:10px;border:none;background-color:#d6dce2\">\n");
      out.write("                </td>\n");
      out.write("                <td style=\"text-align:center;\" colspan=2>\n");
      out.write("                    <input type=\"radio\" name=\"gender${i}\" value=\"Male\" id=\"male${i}\" required>\n");
      out.write("                    <label for=\"male${i}\">Male</label>\n");
      out.write("                    <input type=\"radio\" name=\"gender${i}\" value=\"Female\" id=\"female${i}\" required>\n");
      out.write("                    <label for=\"female${i}\">Female</label>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        `;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            table += `\n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("        <br>\n");
      out.write("    `;\n");
      out.write("\n");
      out.write("            container.innerHTML = table;\n");
      out.write("            payment.innerHTML =  '<a href=\"payment.jsp\"><button>Make Payment</button></a>';\n");
      out.write("        } else {\n");
      out.write("            alert(\"Enter Passenger Values more than 0\");\n");
      out.write("        }}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("    <div class=\"nav\">\n");
      out.write("        <h2>Railway Reservation System</h2>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"nav2\">\n");
      out.write("            ");
 if(user != null) {
      out.write("\n");
      out.write("            <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( user );
      out.write(" &emsp; </h4>\n");
      out.write("            <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("            ");
}else if(admin != null) {
      out.write("\n");
      out.write("            <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( admin );
      out.write(" &emsp; </h4>\n");
      out.write("            <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("            ");
}else{
      out.write("\n");
      out.write("            <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome, Guest! </h4>\n");
      out.write("            ");
}
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    <div class=\"nav1\">\n");
      out.write("        <img src=\"Image/railway_Logo.png\" alt=\"Railway logo\">\n");
      out.write("        <a href=\"index.jsp\" target=\"_parent\">HOME</a>\n");
      out.write("        <!-- <a href=\"login.jsp\">LOGIN</a> -->\n");
      out.write("        <!-- <a href=\"agent.jsp\">AGENT LOGIN</a> -->\n");
      out.write("\n");
      out.write("        <!-- <a href=\"register.jsp\">REGISTER</a> -->\n");
      out.write("        <a href=\"train-schedule.jsp\">TRAIN SCHEDULE</a>\n");
      out.write("        <a href=\"contact.jsp\">CONTACT US</a>\n");
      out.write("        <a href=\"help.jsp\">HELP & SUPPORT</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h1>Train Tickit Booking</h1>\n");
      out.write("    <!-- value of boarding station is passed from booking.jsp -->\n");
      out.write("</div>\n");

    String journeyDate = (String) session.getAttribute("jDate");

    String journeyTime = request.getParameter("train_time");
    session.setAttribute("jTime",journeyTime);

    String totalSeats = request.getParameter("total_seats");
    session.setAttribute("totalSeats",totalSeats);

    String trainName = request.getParameter("train_name");
    session.setAttribute("trainName",trainName);

    String source =(String) session.getAttribute("source");
    String destination = (String) session.getAttribute("destination");

      out.write("\n");
      out.write("<div class=\"bordingDetails\">\n");
      out.write("    <h3>Journey Details</h3>\n");
      out.write("    <div class=\"bording\">\n");
      out.write("        <!-- fetch details from the sessions -->\n");
      out.write("        <h3>Source : ");
      out.print(source);
      out.write("</h3>\n");
      out.write("        <h3>Destination : ");
      out.print(destination);
      out.write("</h3>\n");
      out.write("        <h3>Train Number : ");
      out.print(trainNo);
      out.write("</h3>\n");
      out.write("        <h3>Train Name : ");
      out.print(trainName);
      out.write("</h3>\n");
      out.write("        <h3>Journey Date : ");
      out.print(journeyDate);
      out.write("</h3>\n");
      out.write("        <h3>Journey Time : ");
      out.print(journeyTime);
      out.write("</h3>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<form action=\"passengerDetails?trainNo=");
      out.print(trainNo);
      out.write("&journeyDate=");
      out.print( journeyDate );
      out.write("&journeyTime=");
      out.print( journeyTime);
      out.write("\" method=\"post\">\n");
      out.write("    <div class=\"passengerDetails\">\n");
      out.write("        <h2>Total Number Of Passenger's</h2>\n");
      out.write("        <br>\n");
      out.write("        <input type=\"number\" name=\"totalPassenger\" min=\"1\" max=\"5\" id=\"passenger\" required>\n");
      out.write("\n");
      out.write("        <br><br><br>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"btn\">\n");
      out.write("        <button onclick=\"generatePassenger()\" class=\"search-button\">Add Passsenger</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"details\"></div>\n");
      out.write("\n");
      out.write("    <!-- if the total no of passsenger is > 1 then display -->\n");
      out.write("    <div class=\"payment\" id=\"payment\">\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<footer style=\"background-color: #313131; color: #fff; padding: 20px 0;\">\n");
      out.write("    <div style=\"display: flex; justify-content: space-around; flex-wrap: wrap; padding: 20px;\">\n");
      out.write("\n");
      out.write("        <!-- About Section -->\n");
      out.write("        <div style=\"max-width: 300px;\">\n");
      out.write("            <h4>About Us</h4>\n");
      out.write("            <p>We aim to provide a seamless railway ticket booking experience, offering real-time updates, schedule management, and customer support.</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Quick Links -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Quick Links</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                <li><a href=\"index.jsp\" style=\"color: #fff; text-decoration: none;\">Home</a></li>\n");
      out.write("                <li><a href=\"Booking.jsp\" style=\"color: #fff; text-decoration: none;\">Book Ticket</a></li>\n");
      out.write("                <li><a href=\"train-schedule.html\" style=\"color: #fff; text-decoration: none;\">Train Schedule</a></li>\n");
      out.write("                <li><a href=\"contact.jsp\" style=\"color: #fff; text-decoration: none;\">Contact Us</a></li>\n");
      out.write("                <li><a href=\"help.jsp\" style=\"color: #fff; text-decoration: none;\">FAQs</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Customer Support -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Customer Support</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                <li>Helpline: 7666300048</li>\n");
      out.write("                <li>Email: tejasdevgharkar12@gmail.com</li>\n");
      out.write("                <li><a href=\"feedback.html\" style=\"color: #fff; text-decoration: none;\">Submit Feedback</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Social Media Links -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Follow Us</h4>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Facebook</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Twitter</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff;\">Instagram</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Copyright Section -->\n");
      out.write("    <div style=\"text-align: center; border-top: 1px solid #555; padding: 10px 0;\">\n");
      out.write("        <p>&copy; 2024 Railway Reservation System. All rights reserved.</p>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
