/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-04-18 16:03:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class Booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

     String user = (String) session.getAttribute("FirstName");
     String admin = (String) session.getAttribute("adminName");
    if (user == null){
        response.sendRedirect("/Railway_Reservation_System/login.jsp");
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Booking </title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"Bookingstyle.css\">\n");
      out.write("    <link rel=\"icon\" href=\"Image/logo.png\">\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("    <div class=\"nav\">\n");
      out.write("        <h2>Railway Reservation System</h2>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"nav2\">\n");
      out.write("        ");
 if(user != null) {
      out.write("\n");
      out.write("        <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( user );
      out.write(" &emsp; </h4>\n");
      out.write("        <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("        ");
}else if(admin != null) {
      out.write("\n");
      out.write("        <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( admin );
      out.write(" &emsp; </h4>\n");
      out.write("        <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("        ");
}else{
      out.write("\n");
      out.write("        <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome, Guest! </h4>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"nav1\">\n");
      out.write("        <img src=\"Image/railway_Logo.png\" alt=\"Railway logo\">\n");
      out.write("        <a href=\"index.jsp\" target=\"_parent\">HOME</a>\n");
      out.write("        <!-- <a href=\"login.jsp\">LOGIN</a> -->\n");
      out.write("        <!-- <a href=\"agent.jsp\">AGENT LOGIN</a> -->\n");
      out.write("\n");
      out.write("        <!-- <a href=\"register.jsp\">REGISTER</a> -->\n");
      out.write("        <a href=\"train-schedule.jsp\">TRAIN SCHEDULE</a>\n");
      out.write("        <a href=\"contact.jsp\">CONTACT US</a>\n");
      out.write("        <a href=\"help.jsp\">HELP & SUPPORT</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <br><br>\n");
      out.write("    <div class=\"header\" style=\"letter-spacing: 10px;font-weight: 800\">Train Ticket Booking</div>\n");
      out.write("    <div class=\"sub-header\"></div>\n");
      out.write("    <form action=\"bookTickit\" method=\"POST\">\n");
      out.write("        <div class=\"booking-box\">\n");
      out.write("            <div>\n");
      out.write("                <span class=\"icon\">🚆</span>\n");
      out.write("                <div style=\"font-size: 20px;font-weight: 600;letter-spacing: 5px\">From</div>\n");
      out.write("                <input type=\"text\" name=\"from\" class=\"styled-input\" ");

            String from = (String) session.getAttribute("from");
            if (from != null) {
        
      out.write("\n");
      out.write("                       value=\"");
      out.print( from );
      out.write("\"\n");
      out.write("                    ");

                    session.removeAttribute("from");
            }
        
      out.write(" REQUIRED>\n");
      out.write("            </div>\n");
      out.write("            ");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <span class=\"icon\">🚆</span>\n");
      out.write("                <div style=\"font-size: 20px;font-weight: 600;letter-spacing: 5px\">To</div>\n");
      out.write("                <input type=\"text\" class=\"styled-input\" name=\"to\"\n");
      out.write("                    ");

            String to = (String) session.getAttribute("to");
            if (to != null) {
        
      out.write("\n");
      out.write("                       value=\"");
      out.print( to );
      out.write("\"\n");
      out.write("                    ");

                    session.removeAttribute("to");
            }
        
      out.write("\n");
      out.write("                       required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <span class=\"icon\">📅</span>\n");
      out.write("                <div style=\"font-size: 20px;font-weight: 600;letter-spacing: 5px\">Departure Date</div>\n");
      out.write("                ");

                    // Get today's date
                    java.time.LocalDate today = java.time.LocalDate.now();
                    // Get date 4 months from today
                    java.time.LocalDate maxDate = today.plusMonths(4);

                    // Format them to yyyy-MM-dd for HTML input
                    String minDate = today.toString();
                    String maxDateStr = maxDate.toString();
                
      out.write("\n");
      out.write("                <input type=\"date\" class=\"styled-input\" name=\"departure\"  min=\"");
      out.print( today );
      out.write("\" max=\"");
      out.print( maxDateStr );
      out.write('"');

            String date = (String) session.getAttribute("date");
            if (date != null) {
        
      out.write("\n");
      out.write("                       value=\"");
      out.print( date );
      out.write("\"\n");
      out.write("                       ");

                       session.removeAttribute("date");
            }
        
      out.write("\n");
      out.write("                       required>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <button type=\"submit\" class=\"search-button\">SEARCH</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");

        List<String[]> trainList = (List<String[]>) session.getAttribute("trainList");
        if (trainList != null && !trainList.isEmpty()) {
    
      out.write("\n");
      out.write("    <h2>Available Trains</h2>\n");
      out.write("    <table border=\"1\" style=\"width: 100%\">\n");
      out.write("        <tr style=\"background-color: lightskyblue;height: 60px;letter-spacing: 3px\">\n");
      out.write("            <th>Train No</th>\n");
      out.write("            <th>Train Name</th>\n");
      out.write("            <th>From</th>\n");
      out.write("            <th>To</th>\n");
      out.write("            <th>Departure Time</th>\n");
      out.write("            <th>Frequency</th>\n");
      out.write("            <th>Total Coach</th>\n");
      out.write("            <th colspan=\"2\">Actions</th>\n");
      out.write("\n");
      out.write("        </tr>\n");
      out.write("        ");
 for (String[] train : trainList) { 
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td style=\"font-weight: 700;height: 30px;\">");
      out.print( train[0] );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( train[1] );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( train[2] );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( train[3] );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( train[4] );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( train[5] );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( train[6] );
      out.write("</td>\n");
      out.write("            <td><a href=\"showTrainDetails.jsp\"><button  name=\"");
      out.print( train[0] );
      out.write("\" class=\"btn-one\" >View</button></a></td>\n");
      out.write("            <td><a href=\"BookingPassenger.jsp\"><button  class=\"btn-two\"  name=\"");
      out.print( train[0] );
      out.write("\" >Book</button></a></td>\n");
      out.write("        </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");

        // Clear train list after displaying results to prevent persistence on refresh
        session.removeAttribute("trainList");
    
      out.write("\n");
      out.write("    ");
 } else if (request.getAttribute("trainList") == null) { 
      out.write("\n");
      out.write("    <p>No trains available for the selected route and date.</p>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <br><br>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");

    // Clear train list after displaying results to prevent persistence on refresh
    session.removeAttribute("trainList");

      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<footer style=\"background-color: #313131; color: #fff; padding: 20px 0;\">\n");
      out.write("    <div style=\"display: flex; justify-content: space-around; flex-wrap: wrap; padding: 20px;\">\n");
      out.write("\n");
      out.write("        <!-- About Section -->\n");
      out.write("        <div style=\"max-width: 300px;\">\n");
      out.write("            <h4>About Us</h4>\n");
      out.write("            <p>We aim to provide a seamless railway ticket booking experience, offering real-time updates, schedule management, and customer support.</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Quick Links -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Quick Links</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                <li><a href=\"index.jsp\" style=\"color: #fff; text-decoration: none;\">Home</a></li>\n");
      out.write("                <li><a href=\"Booking.jsp\" style=\"color: #fff; text-decoration: none;\">Book Ticket</a></li>\n");
      out.write("                <li><a href=\"train-schedule.html\" style=\"color: #fff; text-decoration: none;\">Train Schedule</a></li>\n");
      out.write("                <li><a href=\"contact.jsp\" style=\"color: #fff; text-decoration: none;\">Contact Us</a></li>\n");
      out.write("                <li><a href=\"help.jsp\" style=\"color: #fff; text-decoration: none;\">FAQs</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Customer Support -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Customer Support</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                <li>Helpline: 7666300048</li>\n");
      out.write("                <li>Email: tejasdevgharkar12@gmail.com</li>\n");
      out.write("                <li><a href=\"feedback.html\" style=\"color: #fff; text-decoration: none;\">Submit Feedback</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Social Media Links -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Follow Us</h4>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Facebook</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Twitter</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff;\">Instagram</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Copyright Section -->\n");
      out.write("    <div style=\"text-align: center; border-top: 1px solid #555; padding: 10px 0;\">\n");
      out.write("        <p>&copy; 2024 Railway Reservation System. All rights reserved.</p>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
