/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2026-03-31 09:53:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Map;
import java.util.List;

public final class checkPNR_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    Map<String, String> ticketInfo = (Map<String, String>) request.getAttribute("ticketInfo");
    List<Map<String, String>> passengerList = (List<Map<String, String>>) request.getAttribute("passengerList");
    String pnrNo = (String) request.getAttribute("pnrNo");
    String pnrError = (String) request.getAttribute("pnrError");

    boolean showTableData = (ticketInfo != null && passengerList != null) || (pnrError != null);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Check PNR Status</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"pnrStatus.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"nav\">\n");
      out.write("    <h1>Railway Reservation System</h1>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("    <h2>Check PNR Status</h2>\n");
      out.write("    <form action=\"CheckPNR\" method=\"post\">\n");
      out.write("        <label for=\"pnrNumber\">Enter PNR Number:</label>\n");
      out.write("        <br>\n");
      out.write("        <input type=\"text\" id=\"pnrNumber\" name=\"pnrNumber\"\n");
      out.write("               placeholder=\"Enter your PNR...\" maxlength=\"9\" minlength=\"9\" required\n");
      out.write("               value=\"");
      out.print( pnrNo != null ? pnrNo : "" );
      out.write("\">\n");
      out.write("        <br>\n");
      out.write("        <button type=\"submit\">CHECK STATUS</button>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 if (showTableData) { 
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"tableData\">\n");
      out.write("    ");

        ticketInfo = (Map<String, String>) request.getAttribute("ticketInfo");
        passengerList = (List<Map<String, String>>) request.getAttribute("passengerList");
        pnrNo = (String) request.getAttribute("pnrNo");
        pnrError = (String) request.getAttribute("pnrError");
//        boolean showTableData = (ticketInfo != null && passengerList != null) || (pnrError != null);

        if (pnrError != null) {
    
      out.write("\n");
      out.write("    <p style=\"  color: red;text-align: center\">");
      out.print( pnrError );
      out.write("</p>\n");
      out.write("    ");

    } else if (ticketInfo != null && passengerList != null) {
    
      out.write("\n");
      out.write("    <h2>PNR Status for: ");
      out.print( pnrNo );
      out.write("</h2>\n");
      out.write("    <div style=\"font-size: 16px; margin-bottom: 20px;\">\n");
      out.write("        <p><strong>Email:</strong> ");
      out.print( ticketInfo.get("emailID") );
      out.write("</p>\n");
      out.write("        <p><strong>Train Number:</strong> ");
      out.print( ticketInfo.get("train_no") );
      out.write("</p>\n");
      out.write("        <p><strong>Total Amount:</strong> ₹");
      out.print( ticketInfo.get("total_amount") );
      out.write("</p>\n");
      out.write("        <p><strong>Booking Date:</strong> ");
      out.print( ticketInfo.get("booking_date") );
      out.write(" at ");
      out.print( ticketInfo.get("booking_time") );
      out.write("</p>\n");
      out.write("        <p><strong>Status:</strong> ");
      out.print( ticketInfo.get("status") );
      out.write("</p>\n");
      out.write("        <p><strong>Journey Date:</strong> ");
      out.print( ticketInfo.get("journy_date") );
      out.write(" at ");
      out.print( ticketInfo.get("journy_time") );
      out.write("</p>\n");
      out.write("        <p><strong>From:</strong> ");
      out.print( ticketInfo.get("source") );
      out.write(" ➔ <strong>To:</strong> ");
      out.print( ticketInfo.get("destination") );
      out.write("</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <h3>Passenger Details:</h3>\n");
      out.write("    <table border=\"1\" cellpadding=\"10\" cellspacing=\"1\" style=\"width:100%; text-align:center;\">\n");
      out.write("        <tr style=\"    background: linear-gradient(to right, #36d1dc, #5b86e5);letter-spacing: 2px; /* teal-blue */\n");
      out.write(" color: #222121;\">\n");
      out.write("            <th>Seat Number</th>\n");
      out.write("            <th>Passenger Name</th>\n");
      out.write("            <th>Passenger Age</th>\n");
      out.write("            <th>Passenger Gender</th>\n");
      out.write("        </tr>\n");
      out.write("        ");

            for (Map<String, String> passenger : passengerList) {
        
      out.write("\n");
      out.write("        <tr style=\"letter-spacing: 2px;font-weight: 500;\">\n");
      out.write("            <td>");
      out.print( passenger.get("seat_number") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( passenger.get("passenger_name") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( passenger.get("passenger_age") );
      out.write("</td>\n");
      out.write("            <td>");
      out.print( passenger.get("passenger_gender") );
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("        ");

                }
            }
        
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    ");
 }
        session.removeAttribute("ticketInfo");
        session.removeAttribute("passengerList");
        session.removeAttribute("pnrNo");
        session.removeAttribute("pnrError");
    
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("<footer style=\"background-color: #313131; color: #fff; padding: 20px 0;\">\n");
      out.write("    <div style=\"display: flex; justify-content: space-around; flex-wrap: wrap; padding: 20px;\">\n");
      out.write("\n");
      out.write("        <!-- About Section -->\n");
      out.write("        <div style=\"max-width: 300px;\">\n");
      out.write("            <h4>About Us</h4>\n");
      out.write("            <p>We aim to provide a seamless railway ticket booking experience, offering real-time updates, schedule management, and customer support.</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Quick Links -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Quick Links</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                <li><a href=\"index.jsp\" style=\"color: #fff; text-decoration: none;\">Home</a></li>\n");
      out.write("                <li><a href=\"Booking.jsp\" style=\"color: #fff; text-decoration: none;\">Book Ticket</a></li>\n");
      out.write("                <li><a href=\"train-schedule.html\" style=\"color: #fff; text-decoration: none;\">Train Schedule</a></li>\n");
      out.write("                <li><a href=\"contact.jsp\" style=\"color: #fff; text-decoration: none;\">Contact Us</a></li>\n");
      out.write("                <li><a href=\"help.jsp\" style=\"color: #fff; text-decoration: none;\">FAQs</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Customer Support -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Customer Support</h4>\n");
      out.write("            <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                <li>Helpline: 7666300048</li>\n");
      out.write("                <li>Email: tejasdevgharkar12@gmail.com</li>\n");
      out.write("                <li><a href=\"feedback.html\" style=\"color: #fff; text-decoration: none;\">Submit Feedback</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Social Media Links -->\n");
      out.write("        <div style=\"max-width: 200px;\">\n");
      out.write("            <h4>Follow Us</h4>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Facebook</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Twitter</a>\n");
      out.write("            <a href=\"\" target=\"_blank\" style=\"color: #fff;\">Instagram</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Copyright Section -->\n");
      out.write("    <div style=\"text-align: center; border-top: 1px solid #555; padding: 10px 0;\">\n");
      out.write("        <p>&copy; 2024 Railway Reservation System. All rights reserved.</p>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
