/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-04-27 19:36:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.mysql.cj.x.protobuf.MysqlxDatatypes;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.mysql.cj.x.protobuf.MysqlxDatatypes");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String user = (String) session.getAttribute("FirstName");
    String admin = (String) session.getAttribute("adminName");
    session.setAttribute("emailFrom","railway.reservationproject12@gmail.com");
    session.setAttribute("FixedAmount",500);

      out.write('\n');
      out.write('\n');

    String status = (String) session.getAttribute("PasswordChange");
    if (status != null) {

      out.write("\n");
      out.write("<script>\n");
      out.write("    alert(\"");
      out.print( status );
      out.write("\");\n");
      out.write("</script>\n");

        session.removeAttribute("PasswordChange");
    }

      out.write('\n');
      out.write('\n');

    String Success = (String) session.getAttribute("Success");
    if (Success != null) {

      out.write("\n");
      out.write("<script>\n");
      out.write("    alert(\"");
      out.print( Success );
      out.write("\");\n");
      out.write("</script>\n");

        session.removeAttribute("Success");
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("    <link rel=\"icon\" href=\"Image/logo.png\">\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\n");
      out.write("    <title>Railway Reservation System</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header>\n");
      out.write("        <div class=\"nav\">\n");
      out.write("            <h2>Railway Reservation System</h2>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"nav2\">\n");
      out.write("            ");
 if(user != null) {
      out.write("\n");
      out.write("            <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( user );
      out.write(" &emsp; </h4>\n");
      out.write("            <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("            ");
}else if(admin != null) {
      out.write("\n");
      out.write("            <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome,  ");
      out.print( admin );
      out.write(" &emsp; </h4>\n");
      out.write("            <a href=\"logout.jsp\"><i class='bx bx-log-out'></i></a>\n");
      out.write("            ");
}else{
      out.write("\n");
      out.write("            <h4 style=\"text-align: right;\"><i class='bx bx-user'></i> Welcome, Guest! </h4>\n");
      out.write("            ");
}
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class=\"nav1\">\n");
      out.write("            <img src=\"Image/logo.png\" alt=\"Railway logo\">\n");
      out.write("            <a href=\"index.jsp\" target=\"_parent\">HOME</a>\n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 if (user == null && admin == null) { 
      out.write("\n");
      out.write("            <a href=\"login.jsp\">USER LOGIN</a>\n");
      out.write("            <a href=\"agent.jsp\">ADMIN LOGIN</a>\n");
      out.write("            <a href=\"register.jsp\">REGISTER</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 if (admin != null) { 
      out.write("\n");
      out.write("            <a href=\"adminPage.jsp\">ADMIN PAGE</a>\n");
      out.write("            <a href=\"ChangePassword.jsp\">CHANGE PASSWORD</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            ");
 if (user != null) { 
      out.write("\n");
      out.write("            <a href=\"ChangePassword.jsp\">CHANGE PASSWORD</a>\n");
      out.write("            <a href=\"cancelTrainByPassenger.jsp\">CANCEL TICKIT</a>\n");
      out.write("            ");
 } 
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("            <a href=\"checkPNR.jsp\">CHECK PNR</a>\n");
      out.write("            <a href=\"contact.jsp\">CONTACT US</a>\n");
      out.write("            <a href=\"help.jsp\">HELP & SUPPORT</a>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <div class=\"main\">\n");
      out.write("        <h1 id=\"mh1\">\"Your journey, our mission\" </h1>\n");
      out.write("        <br>\n");
      out.write("        <h3 id=\"mh3\">Welcome to Railway Reservation System</h3>\n");
      out.write("        <br>\n");
      out.write("\n");
      out.write("        ");
 if(admin == null){
      out.write("\n");
      out.write("        <span>BOOK YOUR TICKETS HERE</span>\n");
      out.write("        <br><br>\n");
      out.write("        <a href=\"Booking.jsp\"><button class=\"btn\" >BOOK TICKET</button></a>\n");
      out.write("        ");
}
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"main1\">\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/mumbai.jpg\" alt=\"Mumbai\">\n");
      out.write("            <h3>CSMT Station</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/pune.avif\" alt=\"pune\">\n");
      out.write("            <h3>Pune Station</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/benglore.jpg\" alt=\"banglore\">\n");
      out.write("            <h3>Bengaluru Station</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/gujrat.webp\" alt=\"Gujrat\">\n");
      out.write("            <h3>Valsad Station</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/Delhi.jpg\" alt=\"Delhi\">\n");
      out.write("            <h3>Delhi Station</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/kolkatta.jpg\" alt=\"kolkatta\">\n");
      out.write("            <h3>Kolkatta Station</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/havada.jpg\" alt=\"havada\">\n");
      out.write("            <h3>Hawada Station</h3>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"i1\">\n");
      out.write("            <img src=\"Image/chenai.jpg\" alt=\"chenai\">\n");
      out.write("            <h3>Chennai Station</h3>\n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("    <div class=\"line\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"info\">\n");
      out.write("        <div class=\"left\">\n");
      out.write("            <p>A <i><b>Railway Reservation System </b></i>project is a software application designed to manage and automate the ticket booking and scheduling processes for railway services. It typically includes features for passengers to book tickets, manage reservations, and access train schedules.</p>\n");
      out.write("            <br>\n");
      out.write("            <h2>Project Overview</h2>\n");
      out.write("            <br>\n");
      out.write("            <p>The Railway Reservation System aims to streamline the process of reserving train tickets and managing passenger details, making it more efficient and user-friendly. The system can be developed as a desktop, web, or mobile application.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"right\">\n");
      out.write("                <img src=\"Image/dhudhsagar.jpg\" alt=\"Waterfall\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"line\"></div>\n");
      out.write("        <div class=\"team1\">\n");
      out.write("            <h1>Team Members</h1>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"team\">\n");
      out.write("            \n");
      out.write("            <div class=\"t1\">\n");
      out.write("                <img src=\"Image/Tejas.jpg\" alt=\"Tejas Devgharkar\" >\n");
      out.write("                <h3 id=\"tag\">Tejas Devgharkar</h3>\n");
      out.write("                <span id=\"tag\">C 90</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"t1\">\n");
      out.write("                <img src=\"Image/IMG_20241221_202000.jpg\" alt=\"Pradnya mahadik\" >\n");
      out.write("                <h3 id=\"tag\">Pradnya Mahadik</h3>\n");
      out.write("                <span id=\"tag\">C 11</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"t1\">\n");
      out.write("                <img src=\"Image/IMG_20241221_201707.jpg\" alt=\"Anisa Pathan\" >\n");
      out.write("                <h3 id=\"tag\">Anisa Pathan</h3>\n");
      out.write("                <span id=\"tag\">C 86</span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <footer style=\"background-color: #313131; color: #fff; padding: 20px 0;\">\n");
      out.write("            <div style=\"display: flex; justify-content: space-around; flex-wrap: wrap; padding: 20px;\">\n");
      out.write("              \n");
      out.write("              <!-- About Section -->\n");
      out.write("              <div style=\"max-width: 300px;\">\n");
      out.write("                <h4>About Us</h4>\n");
      out.write("                <p>We aim to provide a seamless railway ticket booking experience, offering real-time updates, schedule management, and customer support.</p>\n");
      out.write("              </div>\n");
      out.write("          \n");
      out.write("              <!-- Quick Links -->\n");
      out.write("              <div style=\"max-width: 200px;\">\n");
      out.write("                <h4>Quick Links</h4>\n");
      out.write("                <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                  <li><a href=\"index.jsp\" style=\"color: #fff; text-decoration: none;\">Home</a></li>\n");
      out.write("                  <li><a href=\"Booking.jsp\" style=\"color: #fff; text-decoration: none;\">Book Ticket</a></li>\n");
      out.write("                  <li><a href=\"train-schedule.html\" style=\"color: #fff; text-decoration: none;\">Train Schedule</a></li>\n");
      out.write("                  <li><a href=\"contact.jsp\" style=\"color: #fff; text-decoration: none;\">Contact Us</a></li>\n");
      out.write("                  <li><a href=\"help.jsp\" style=\"color: #fff; text-decoration: none;\">FAQs</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("          \n");
      out.write("              <!-- Customer Support -->\n");
      out.write("              <div style=\"max-width: 200px;\">\n");
      out.write("                <h4>Customer Support</h4>\n");
      out.write("                <ul style=\"list-style-type: none; padding: 0;\">\n");
      out.write("                  <li>Helpline: 7666300048</li>\n");
      out.write("                  <li>Email: tejasdevgharkar12@gmail.com</li>\n");
      out.write("                  <li><a href=\"feedback.html\" style=\"color: #fff; text-decoration: none;\">Submit Feedback</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("          \n");
      out.write("              <!-- Social Media Links -->\n");
      out.write("              <div style=\"max-width: 200px;\">\n");
      out.write("                <h4>Follow Us</h4>\n");
      out.write("                <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Facebook</a>\n");
      out.write("                <a href=\"\" target=\"_blank\" style=\"color: #fff; margin-right: 10px;\">Twitter</a>\n");
      out.write("                <a href=\"\" target=\"_blank\" style=\"color: #fff;\">Instagram</a>\n");
      out.write("              </div>\n");
      out.write("          \n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Copyright Section -->\n");
      out.write("            <div style=\"text-align: center; border-top: 1px solid #555; padding: 10px 0;\">\n");
      out.write("              <p>&copy; 2024 Railway Reservation System. All rights reserved.</p>\n");
      out.write("            </div>\n");
      out.write("          </footer>\n");
      out.write("          \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
